export const SUPPORTED_CURRENCIES = {
    INR: "Indian Rupee",
    USD: "US Dollar",
    EUR: "Euro",
    GBP: "British Pound",
    AUD: "Australian Dollar",
    CAD: "Canadian Dollar",
    CHF: "Swiss Franc",
    JPY: "Japanese Yen",
    CNY: "Chinese Yuan Renminbi",
    MYR: "Malaysian Ringgit",
    ZAR: "South African Rand",
    NZD: "New Zealand Dollar",
    RUB: "Russian Ruble",
    BRL: "Brazilian Real",
    MXN: "Mexican Peso",
    THB: "Thai Baht",
    SGD: "Singapore Dollar",
    AED: "UAE Dirham",
    SAR: "Saudi Riyal",
    KWD: "Kuwaiti Dinar",
    BHD: "Bahraini Dinar",
    OMR: "Omani Rial",
};
