export const SUPPORTED_CURRENCIES = {
    INR: "Indian Rupee",
    USD: "US Dollar",
    EUR: "Euro",
    GBP: "British Pound",
    AUD: "Australian Dollar",
    CAD: "Canadian Dollar",
    SGD: "Singapore Dollar",
    JPY: "Japanese Yen",
    CNY: "Chinese Yuan",
    CHF: "Swiss Franc",
    AED: "UAE Dirham",
    SAR: "Saudi Riyal",
    NZD: "New Zealand Dollar",
    SEK: "Swedish Krona",
    NOK: "Norwegian Krone",
    DKK: "Danish Krone",
    ZAR: "South African Rand",
    THB: "Thai Baht",
    MYR: "Malaysian Ringgit",
    KRW: "South Korean Won",
    IDR: "Indonesian Rupiah"
};
